default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

  #今回は設定内容がわかりやすいよう、元のコメントは削除。開発環境およびテスト環境ではMySQLが、本番環境ではPostgreSQLが使用されるようになる。
  #これは、Ruby on Railsアプリケーションのデータベース接続設定ファイルの例です。YAML形式で書かれています。
#最初に、デフォルトの設定が&defaultで定義されています。これは、encodingをUTF-8に設定し、接続プールの最大スレッド数を環境変数RAILS_MAX_THREADSの値に設定します。
#その後、development、test、productionという環境ごとの設定が定義されています。それぞれの設定は、<<: *defaultを使用してデフォルトの設定を継承しています。
#developmentとtest環境では、MySQLデータベースに接続するための設定が定義されています。adapterはmysql2を使用し、ユーザー名とパスワードはrootと空白に設定されています。また、データベース名はそれぞれajax_app_developmentとajax_app_testです。
#production環境では、PostgreSQLデータベースに接続するための設定が定義されています。adapterはpostgresqlを使用し、接続URLは環境変数DATABASE_URLの値を使用しています。このように、本番環境ではデータベース接続情報を環境変数から取得することが一般的です。#